"""banfieldbio_compliance — public compliance documentation library.

Hosts safety / regulatory documents (SDS, EPA labels, DOT paperwork,
COA when applicable) and constructs URLs / per-item HTML / per-shipment
PDFs that QR codes on outbound research shipments resolve to.

Public API:

    from banfieldbio_compliance import (
        SiteConfig,
        load_config,
        SdsEntry,
        SdsIndex,
        load_index,
        save_index,
        sds_url,
        item_url,
        library_index_url,
        render_qr_png,
        render_qr_bytes,
        render_item_page,
        render_library_index,
    )

Note: per-shipment HTML pages are intentionally NOT in the public API.
Per-shipment artifacts are PDFs generated by the private ORS tool and
written into ``docs/shipment/<uuid>.pdf`` with opaque UUID tokens.
"""

from banfieldbio_compliance.config import SiteConfig, load_config
from banfieldbio_compliance.index import SdsEntry, SdsIndex, load_index, save_index
from banfieldbio_compliance.landing import render_item_page, render_library_index
from banfieldbio_compliance.qr import render_qr_bytes, render_qr_png
from banfieldbio_compliance.urls import item_url, library_index_url, sds_url

__all__ = [
    "SiteConfig",
    "load_config",
    "SdsEntry",
    "SdsIndex",
    "load_index",
    "save_index",
    "sds_url",
    "item_url",
    "library_index_url",
    "render_qr_png",
    "render_qr_bytes",
    "render_item_page",
    "render_library_index",
]

__version__ = "0.1.0"
