"""banfieldbio_compliance — public compliance documentation library.

Hosts safety / regulatory documents (SDS, EPA labels, DOT paperwork,
COA when applicable) for materials explicitly classified as public, and
renders the per-item pages and library index that QR codes resolve to.

Public API:

    from banfieldbio_compliance import (
        SiteConfig,
        load_config,
        SdsEntry,
        SdsIndex,
        load_index,
        save_index,
        sds_url,
        item_url,
        library_index_url,
        render_qr_png,
        render_qr_bytes,
        render_item_page,
        render_library_index,
    )

Note: shipment artifacts are not part of this package or this site. They
are generated by the private ORS tool and served from the gated endpoint.
Nothing here constructs a public URL for one.

Note: this package does not decide what may be published. ORS owns that
decision and is the only writer of ``data/index.json``; every entry must
declare ``disclosure: "public"`` and loading fails otherwise.
"""

from banfieldbio_compliance.config import SiteConfig, load_config
from banfieldbio_compliance.index import SdsEntry, SdsIndex, load_index, save_index
from banfieldbio_compliance.landing import render_item_page, render_library_index
from banfieldbio_compliance.qr import render_qr_bytes, render_qr_png
from banfieldbio_compliance.urls import item_url, library_index_url, sds_url

__all__ = [
    "SiteConfig",
    "load_config",
    "SdsEntry",
    "SdsIndex",
    "load_index",
    "save_index",
    "sds_url",
    "item_url",
    "library_index_url",
    "render_qr_png",
    "render_qr_bytes",
    "render_item_page",
    "render_library_index",
]

__version__ = "0.1.0"
