"""Static HTML page generators.

Two page types are publicly exposed:

* **Per-item** — reference page for a single Inv#, info plus an SDS button.
  These are the stable indirection layer: per-shipment PDFs link here, not
  directly to manufacturer URLs, so link-rot can be repaired in one place
  (update `data/index.json`, redeploy Pages).
* **Library index** — landing page at the site root listing every item in
  the library, searchable with a simple input.

Per-shipment landing pages are NOT generated by this module. Per-shipment
artifacts are PDFs at opaque UUID-token paths, generated by the private
ORS tool's publisher and written into ``docs/shipment/<uuid>.pdf``.

All templates are inline Jinja strings. No external template files — keeps
the deploy simple. HTML is escaped by Jinja autoescape. Pages are
phone-first: a single-column layout that works at 320px and reads cleanly
on desktop too.
"""

from __future__ import annotations

import logging
from datetime import date, datetime
from pathlib import Path

from jinja2 import Environment, select_autoescape

from banfieldbio_compliance.config import SiteConfig
from banfieldbio_compliance.index import SdsEntry, SdsIndex
from banfieldbio_compliance.urls import item_url, library_index_url, sds_url

logger = logging.getLogger(__name__)

_jinja = Environment(autoescape=select_autoescape(["html", "xml"]))


_BASE_HEAD = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="{{ assets_base }}/assets/style.css">
</head>
<body>
<header>
  <a class="home" href="{{ site_home }}">BanfieldBio Compliance</a>
</header>
<main>
"""

_BASE_FOOT = """
</main>
<footer>
  <p>
    Compliance reference. Always verify the document matches the label on
    the container you received. Generated {{ generated_at }}.
  </p>
</footer>
</body>
</html>
"""

_ITEM_TMPL = _jinja.from_string(
    _BASE_HEAD
    + """
<h1>{{ entry.name }}</h1>
<p class="meta">
  <span class="inv">{{ entry.inv_num }}</span>
  {% if entry.cas_num %} &middot; CAS {{ entry.cas_num }}{% endif %}
  {% if entry.manufacturer %} &middot; {{ entry.manufacturer }}{% endif %}
</p>
{% if entry.sds_version %}
  <p class="version">SDS version: {{ entry.sds_version }}</p>
{% endif %}
<div class="item-actions">
  {% if sds_link %}
    <a class="btn sds" href="{{ sds_link }}"
       {% if not sds_is_mirror %}rel="noopener" target="_blank"{% endif %}>
      View SDS{% if not sds_is_mirror %} (external){% endif %}
    </a>
  {% else %}
    <p class="no-sds">No SDS on file for this item.</p>
  {% endif %}
</div>
"""
    + _BASE_FOOT
)

_INDEX_TMPL = _jinja.from_string(
    _BASE_HEAD
    + """
<h1>Compliance Library</h1>
<p class="meta">{{ entry_count }} item(s) in the library.</p>
<input type="search" id="q" placeholder="Filter by Inv#, name, or CAS…" autocomplete="off">
<table class="library">
  <thead>
    <tr><th>Inv#</th><th>Name</th><th>CAS</th><th>SDS</th></tr>
  </thead>
  <tbody>
  {% for row in rows %}
    <tr>
      <td><a href="{{ row.item_href }}">{{ row.inv_num }}</a></td>
      <td>{{ row.name }}</td>
      <td>{{ row.cas_num or "" }}</td>
      <td>
        {% if row.sds_link %}
          <a href="{{ row.sds_link }}"
             {% if not row.sds_is_mirror %}rel="noopener" target="_blank"{% endif %}>
            {{ "mirror" if row.sds_is_mirror else "external" }}
          </a>
        {% else %}
          &mdash;
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
<script>
  // No framework; tiny progressive-enhancement filter.
  const q = document.getElementById('q');
  const rows = document.querySelectorAll('table.library tbody tr');
  q && q.addEventListener('input', () => {
    const needle = q.value.toLowerCase();
    rows.forEach(r => {
      r.style.display = r.textContent.toLowerCase().includes(needle) ? '' : 'none';
    });
  });
</script>
"""
    + _BASE_FOOT
)


def _generated_at() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def render_item_page(
    config: SiteConfig,
    entry: SdsEntry,
    out_dir: Path,
) -> Path:
    """Write ``<out_dir>/<item_dir>/<INV#>/index.html``."""
    dest_dir = out_dir / config.item_dir / entry.inv_num.upper()
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / "index.html"
    link = sds_url(config, entry)
    html = _ITEM_TMPL.render(
        title=f"{entry.inv_num} — {entry.name}",
        assets_base="../..",
        site_home="../../",
        entry=entry,
        sds_link=link,
        sds_is_mirror=entry.has_mirror,
        generated_at=_generated_at(),
    )
    dest.write_text(html, encoding="utf-8")
    logger.info("Wrote item landing page to %s", dest)
    return dest


def render_library_index(
    config: SiteConfig,
    index: SdsIndex,
    out_dir: Path,
) -> Path:
    """Write the library-root index page at ``<out_dir>/index.html``."""
    rows = []
    for entry in index.sorted_by_inv_num():
        link = sds_url(config, entry)
        rows.append(
            {
                "inv_num": entry.inv_num,
                "name": entry.name,
                "cas_num": entry.cas_num,
                "sds_link": link,
                "sds_is_mirror": entry.has_mirror,
                "item_href": item_url(config, entry.inv_num),
            }
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / "index.html"
    html = _INDEX_TMPL.render(
        title="BanfieldBio Compliance Library",
        assets_base=".",
        site_home=library_index_url(config),
        rows=rows,
        entry_count=len(rows),
        generated_at=_generated_at(),
    )
    dest.write_text(html, encoding="utf-8")
    logger.info("Wrote library index to %s", dest)
    return dest


# Re-export a dummy `date` to keep the module self-contained when importers
# type-check the ``SdsEntry.added_on`` field. Some IDEs prefer the import
# reference to be present at module level.
_ = date
